Feature/add best practices workflow
ZupIT/beagle-android pull request #44
Opened 2021-11-08 18:11 UTC by carlossteinzup

### Related Issues

Update / add opensource security workflows at Beagle Android repository
https://app.shortcut.com/devrelopensource/story/179033/scorecard-beagle-android

### Description and Example

Adds validation actions for:
- DCO, 
- License, 
- Dependabot, 
- Horusec.

### Checklist

Please, check if these important points are met using `[x]`:

- [ ] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [ ] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [ ] I am willing to follow-up on review comments in a timely manner.
- [ ] I have made the documentation changes or I created an issue explaining how to document this change on [Docs issues](https://github.com/ZupIT/beagle-docs/issues). Please link the issue here:

[PR Guide]: https://github.com/ZupIT/beagle-android/blob/main/doc/contributing/pull_requests.md

2021-11-08 18:12 UTC, botbeaglezup commented
<!--
  1 Error: The title of PR not follow the...
  0 Warnings
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">The title of PR not follow the rules of: https://www.conventionalcommits.org/en/v1.0.0/</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-11-08 18:45 UTC, botbeaglezup commented
<!--
  1 Error: Tests have failed, see below f...
  0 Warnings
  0 Messages
  2 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>

### Tests: 

Name | Classname | Time|
--- | --- | ---|
Should call Analytics Service with correct parameters | br.com.zup.beagle.android.view.viewmodel.AnalyticsViewModelTest$CreateActionReport | 0.38|


### Tests: 

Name | Classname | Time|
--- | --- | ---|
Should call Analytics Service with correct parameters | br.com.zup.beagle.android.view.viewmodel.AnalyticsViewModelTest$CreateScreenReport | 0.387|


<p align="right" data-meta="generated_by_android">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-11-30 18:51 UTC, hectorcustodiozup requested changes

2021-11-30 18:51 UTC, hectorcustodiozup commented on .github/workflows/horusec-pr.yml
>          env:
```suggestion
```

2021-11-30 18:51 UTC, hectorcustodiozup commented on .github/workflows/horusec-pr.yml
>            HORUSEC_CLI_REPOSITORY_AUTHORIZATION: ${{ env.BEAGLE_CORE_SECURITY_HORUSEC_CLI_REPOSITORY_AUTHORIZATION }}
```suggestion
```

2021-12-01 20:42 UTC, carlossteinzup commented
Did the modifications. Can you review again please?

2021-12-02 13:10 UTC, hectorcustodiozup approved these changes

2021-12-02 13:10 UTC, merged